apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-training-deployment
  namespace: ml-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-training-app
  template:
    metadata:
      labels:
        app: ml-training-app
    spec:
      containers:
      - name: ml-training-container
        image: novach/your-app:latest  # Use the image built and pushed from the CI/CD pipeline
        command: ["python", "test_train.py"]
        volumeMounts:
        - mountPath: "/app/output"
          name: output-volume
      volumes:
      - name: output-volume
        persistentVolumeClaim:
          claimName: ml-training-pvc

