apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlc-pvc
  namespace: c2-namespace  # Optional: specify if using a namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

