apiVersion: v1
kind: Service
metadata:
  name: c1-service
  namespace: <your-namespace>  # Optional: specify if using a namespace
spec:
  selector:
    app: mlc-app
  type: LoadBalancer  # Use LoadBalancer if on a cloud provider, or NodePort for on-prem
  ports:
  - protocol: TCP
    port: 80         # External port
    targetPort: 5001 # Port where MLflow is running in the container

